### ISSUE TITLE
Revert icons via Git LFS ASAP

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-qgis#22]
I cannot exactly find which commit is responsible, but the icon SVGs have been replaced with Git LFS placeholders.

This was a bad decision, as the plugin repository now contains a ZIP with Git LFS placeholders rather than the actual SVG's.
(Also, SVG's are text and small: there is absolutely no reason to use Git LFS on this repo whatsoever!)

**Comment by JoerivanEngelen** [comment]
Fixed in 8be7fbc058e31e1e4a5bfa663a90927b164c1de0

**Comment by JoerivanEngelen** [comment]
Btw, for future reference, if we ever have to untrack git lfs files, this worked: https://github.com/git-lfs/git-lfs/issues/3026#issuecomment-696697599
