### ISSUE TITLE
Current plugin on qgis-plugin repo is broken

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-qgis#23]
Due to:
https://github.com/Deltares/imod-qgis/issues/22

No actual icons are included in the ZIP on the plugin repo, due to Git LFS.
The plugin will start, but on certain widgets it will give an error, as (clearly) no icon can be found.

#22 needs to be fixed, and then a new version should be uploaded to the repo.

**Comment by JoerivanEngelen** [comment]
I added a batch script to package locally, similar to the [bash script in the crayfish plugin](https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/master/package.bash). 

I tested it locally in QGIS and it worked for me. Plugin v0.2.2  is now waiting for approval.
