### ISSUE TITLE
Supported versions: too opaque

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-qgis#24]
The installation guide (https://deltares.github.io/iMOD-Documentation/viewer_install.html) mentions:

> You can download the standalone QGIS setup on the QGIS website We recommend downloading a QGIS version > 3.18 here

There are at least two problems with this:

* It tells you a version that is NOT supported (3.18). I think it's more common/easier-to-parse to say which version IS supported (>=3.20). Currently, you read 3.18, and then have to decide it's not the one you want.
* 3.18 is not necessarily clear either: is the entirety of 3.18 not allowed, or does it implicitly stand for 3.18.0? And would 3.18.2 maybe be supported?

Secondly, we should make a plan for whether we'll stick to the latest changes or not. If we do stick to latest changes, we need to assign versions carefully to the plugin. 
My personal preference is to stick to LTR if possible. But this is something we might be able to test: if new versions of QGIS do not constantly break the plugin, we could stick to latest changes.

On the upside, I think the notice has been removed that the Mesh stuff may be changed without notice?
https://qgis.org/pyqgis/master/core/QgsMeshDataset.html

Second, we need a careful changelog detailing which changes in QGIS necessitate changes in the plugin.

**Comment by JoerivanEngelen** [comment]
FYI: The warning about API changes for meshes is still present on some pages, e.g.:
https://qgis.org/pyqgis/master/core/QgsMeshLayer.html
So I'm not sure...
