### ISSUE TITLE
timeseries: snapping tolerance for select points

### ISSUE THREAD

**Issue by visr** [Deltares/imod-qgis#40]
In the Ribasim-QGIS plugin we use big blue circles for the basins. Users expect that clicking anywhere on this icon should be enough to select points, but in reality it seems that you have to click very close to the center of the icon, which can be confusing.

https://deltares.github.io/Ribasim/qgis/#inspect-results

**Comment by Huite** [comment]
It seems like this has been an issue for a long time, looking at this issue from 12 years ago (!):

https://issues.qgis.org/issues/3806
https://github.com/qgis/QGIS/issues/13864

Best to document clearly that dragging is the most practical mechanism.

**Comment by visr** [comment]
Ok, documented in https://github.com/Deltares/Ribasim/commit/8e82303ae408eb084f9fab9ed48540b29e4efc84.
