### ISSUE TITLE
IDF conversion fails silently if there is no write permission

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-qgis#51]
When opening an IDF, it is converted to an equivalent geotiff file, which is written next to the IDF.

However, if the user does not have writing permission, GDAL will fail silently (since the Python bindings of GDAL do not raise exceptions). Then the raster type will be None, and setGeoTransform will fail instead, which is a very confusing error message.

What we should do instead, I think, is check whether GDAL has not failed, then raise that specific error ("IDF could not be converted to GeoTIFF"), which is probably still general, but less cryptic than "NoneType has no attribute setGeoTransform".

**Comment by JoerivanEngelen** [comment]
Duplicate from https://github.com/Deltares/imod-qgis/issues/67
