### ISSUE TITLE
TypeError: 'method' object is not connected in timeseries widget

### ISSUE THREAD

**Issue by visr** [Deltares/imod-qgis#54]
I get this after some time with an open timeseries widget with data in Arrow files. Not sure why I didn't get this earlier.

```
An error has occurred while executing Python code: 

TypeError: 'method' object is not connected 
Traceback (most recent call last):
  File "C:\Users/visser_mn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\imodqgis\timeseries\timeseries_widget.py", line 318, in hideEvent
    layer.selectionChanged.disconnect(self.on_select)
TypeError: 'method' object is not connected


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.2-Lima Lima, c0b8833964 
```

When this happens, the timeseries widget stops working. Closing the widget and re-opening makes it work again. There is no need to re-associate the data.

**Comment by JoerivanEngelen** [comment]
Thanks for posting this issue, do you have some Arrow data you can share with me with which I can debug?

**Comment by JoerivanEngelen** [comment]
I also ran into this, it seems independent of using Arrow data.

**Comment by JoerivanEngelen** [comment]
I found how to reproduce this error:
To reproduce this issue:

- Select vector data in timeseries widget
- Hide QGIS
- Unhide QGIS
- Hide QGIS
