### ISSUE TITLE
Access violation on starting Times Series widget

### ISSUE THREAD

**Issue by visr** [Deltares/imod-qgis#68]
This happens sometimes when starting the widget, though I cannot really find a pattern yet when. It crashes QGIS.

```
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00007844 (most recent call first):
  File "D:\Ribasim\.pixi\qgis_env\profiles\default/python/plugins\imodqgis\timeseries\timeseries_widget.py", line 457 in on_layer_changed
    self.iface.setActiveLayer(layer)
  File "D:\Ribasim\.pixi\qgis_env\profiles\default/python/plugins\imodqgis\timeseries\timeseries_widget.py", line 284 in __init__
    self.on_layer_changed()
  File "D:\Ribasim\.pixi\qgis_env\profiles\default/python/plugins\imodqgis\imod_plugin.py", line 132 in toggle_timeseries
    widget = ImodTimeSeriesWidget(self.timeseries_widget, self.iface)
```

```
QGIS version 3.34.3-Prizren
Qt version 5.15.8
Python version 3.11.7

Active Python plugins
imodqgis 0.5.0
ribasim_qgis 2024.2.0
```

**Comment by Huite** [comment]
Isn't this the same issue we run into with the ribasim-qgis?

**Comment by visr** [comment]
This happens when starting the Time Series widget, and https://github.com/Deltares/Ribasim/issues/993 happens when starting the Ribasim QGIS plugin, with a different stack trace.

**Comment by visr** [comment]
Between the two of them using Ribasim QGIS is like walking a minefield :(
This one explodes less often than the other one though.

**Comment by Huite** [comment]
I didn't notice this in the past: I wonder if it's due changes in more recent QGIS versions...

**Comment by visr** [comment]
Closing this for now as I've played around a bit with 3.34.4 (the new LTR) and 3.36.0, and I haven't seen this issue there yet. Could've just been lucky though, https://github.com/Deltares/Ribasim/issues/993 still happens on both.
