### ISSUE TITLE
Cross-section widget: Plotted cross-section data not redrawn after switching time

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod-qgis#72]
@rubencalje reported in #65:

From the docs:

> For time dependent data, when the Temporal Controller Panel is turned on, the cross-section plot is automatically updated when a different moment in time is selected.

His experience:

> This is not my experience. The cross-section plot only updates to a new selected time when I draw another cross-section line using the "Select location"-button. The main map does update when I select a different moment in time. Is this a known issue, or am I doing something wrong?

So it appears data is not automatically redrawn when selecting different timestamps.

**Comment by JoerivanEngelen** [comment]
Some triage is required: @rubencalje, have you tested if this was only the case with line data or also with the PColorMesh data (i.e. "as line data" checked off?). I'm not sure I have tested the plugin for transient line data. It could also be that something changed internally in QGIS which breaks this, which QGIS version are you using?

**Comment by rubencalje** [comment]
Thanks for generating a separate issue. 

I just checked. You are right, this issue is only the case when the data is drawn as lines. When the data is draws as PColorMesh data the plot is updated when the selected time is changed.

I have tested this in QGIS version 3.32.0-Lima.
